### ISSUE TITLE
Support for ISO 3 letters languages kab and ber

### ISSUE THREAD

**Issue by BoFFire** [mapbox/mapbox-gl-language#16]
Hello,
POI names such as name:kab, name:ber (in Algeria and Morroco, for example) are not displayed. How can I make Mapbox-gl-language display them ?
Same issue is happening when using Mozilla Firefox in kabyle language : https://www.mozilla.org/kab/
Best regards,

**Comment by 1ec5** [comment]
Although names in these languages are present in OpenStreetMap, Mapbox GL JS is typically used with the [Mapbox Streets source](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/), which provides only a limited selection of `name_*` fields (in addition to the local-language `name` field). For the time being, until Mapbox Streets source adds additional languages, you can export the names from OpenStreetMap, import them into Mapbox Studio as a dataset, and load them into GL JS as a vector source.

**Comment by BoFFire** [comment]
Hello,
Thank you for the answer. I thought it was easy to support minority languages all over the Web but it seems another debate.
Can I ask how comes name_zh-Hans is displayable and not a name_kab technically.
Thank you.

**Comment by 1ec5** [comment]
The Mapbox Streets source is limited in how many languages it can support due to the amount of space that each language adds to the vector tiles. The more languages supported, the longer it takes to load each tile. Currently, for any given feature, the local name, English name, Spanish name, Simplified Chinese name, etc. is included, even if they all end up being identical. That’s because, until recently, GL JS lacked the ability to say “use the Spanish name, but fall back to the English name if the Spanish name is unavailable”.

Expressions solved this problem, so once all the Mapbox GL libraries support expressions (including on the mobile SDKs), then it’ll be technically possible for the Streets source to support more languages without bloating the tiles. That said, GL JS is compatible with any vector tileset that conforms to the Mapbox Vector Tile Specification, not just Mapbox Streets. So you may be able to use third-party vector tiles with GL JS if you need Kabyle and Berber support right away.

Hope this helps! If you have any additional questions or need help bringing custom or third-party vector tiles into GL JS, please contact the [Mapbox Support](https://www.mapbox.com/contact/support/) team.

**Comment by BoFFire** [comment]
Thank you again,
From OpenStreetMap Algeria
