### ISSUE TITLE
no types for typescript 

### ISSUE THREAD

**Issue by asifmehmood101** [mapbox/mapbox-gl-language#51]
is there any packages that help to generate types for this package

**Comment by chriszrc** [comment]
Sadly it appears there isn't a types package yet :( 
But for most people, creating something like a global.d.ts at the root of their src folder and adding:

```
declare module "@mapbox/mapbox-gl-language";
```

Should be enough, since usage is pretty simple. If you really want type checking for the constructor options, you can add them in your own local typings:

```
import { IControl } from "mapbox-gl";

declare module "@mapbox/mapbox-gl-language" {
  export default class MapboxLanguage implements IControl {
    constructor(options?: {
      defaultLanguage: string;
      supportedLanguages: string[];
      //...etc
    });
  }
}
```
